# See http://pre-commit.com/#python
# See https://github.com/pre-commit/pre-commit-hooks
# Run 'pre-commit install' to install the pre-commit hooks
repos:

# See also https://adamj.eu/tech/2021/09/16/introducing-django-upgrade/
- repo: https://github.com/asottile/pyupgrade
  rev: v2.26.0
  hooks:
    - id: pyupgrade
      args: [ --py39-plus ]

- repo: https://github.com/adamchainz/django-upgrade
  rev: 1.2.0
  hooks:
    - id: django-upgrade
      args: [--target-version, "3.2"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: detect-private-key
  # black handles quoting
  # - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
    exclude: (.csv|.tsv)$
  - id: pretty-format-json
    args: ['--no-sort-keys', '--autofix']
  # don't commit directly to main or master
  - id: no-commit-to-branch

- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
  - id: black
    language_version: python3.9
    # django migrations
    exclude: migrations/

# flake8 after black, so black can fix formatting first
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    # django migrations
    exclude: migrations/

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args:
        # fill in source directories
        - --src=src
        # See also https://jugmac00.github.io/blog/isort-and-pre-commit-a-friendship-with-obstacles/
        - --filter-files
        # django migrations
        - --skip-glob=*/migrations/*.py
        # line length must match black and flake8
        - --profile=black

- repo: https://github.com/rtts/djhtml
  rev: '3.0.2'
  hooks:
    - id: djhtml
    - id: djcss
    - id: djjs

# possibly re-enable pylint.  it's very picky.
# - repo: https://github.com/PyCQA/pylint
#   rev: v2.16.0b1
#   hooks:
#     - id: pylint
#       args:
#         - --disable=consider-using-in
#         - --disable=disallowed-name
#         - --disable=fixme
#         - --disable=import-error
#         - --disable=logging-fstring-interpolation
#         - --disable=missing-class-docstring
#         - --disable=missing-function-docstring
#         - --disable=missing-module-docstring
#         - --disable=no-name-in-module
#         - --disable=no-member
#         - --disable=too-few-public-methods
#         - --disable=too-many-instance-attributes
#         - --disable=too-many-arguments
#         - --disable=too-many-branches
#         - --disable=too-many-locals
#         - --disable=unpacking-non-sequence
#         # re-enable these args
#         - --disable=unused-argument
#         - --disable=protected-access
#         - --disable=invalid-name
#         - --disable=raise-missing-from
#         - --disable=wrong-import-order
#         - --disable

# leave mypy out for now
#- repo: https://github.com/pre-commit/mirrors-mypy
#  rev: v0.942
#  hooks:
#    - id: mypy
#      additional_dependencies:
#        - types-requests
#      args:
#        - --ignore-missing-imports

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.4.2
  hooks:
  - id: forbid-crlf
  # don't just remove, seems dangerous
  # - id: remove-crlf
  - id: forbid-tabs
    # tests.py has a test with a tab in it
    # jquery is auto-generated code
    exclude: (.tsv)$
  # don't just remove, seems dangerous
  # - id: remove-tabs

- repo: local
  hooks:
  # for Django templates
  - id: no-img-src-slash
    name: no bare img static
    description: Enforce that image src doesn't start with a slash
    entry: 'img src="/'
    language: pygrep
    # templates
    files: '.html$'

  # for Django templates
  - id: no-slash-assets
    name: no direct /static/ include
    description: Enforce that we don't include /static/ directly
    entry: '/static/'
    language: pygrep
    # templates
    files: '.html$'
